---
title: "Graphics with ggplot2"
author: "OM"
date: "March 12, 2018"
output: html_document
---

## Learning ggplot2
```{r, echo = FALSE}
library(tidyverse)
```
#can specify which package function is being when called when conficts
stats::filter()

```{r}
mpg
```
```{r}
ggplot(data=mpg, mapping = aes(x = displ, y = hwy)) + geom_point()

#my_plot <- ggplot(data=mpg) + geom_point(mapping = aes(x = displ, y = hwy))

```

#operators like + must be last on the line

```{r}
ggplot(data=mpg, mapping = aes(x = displ, y = hwy, shape = class)) + geom_point(alpha = 0.4)

```
```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class)) + geom_point()
```

Make a scatterplot of "hwy" vs "cty" mileage with different sized points representing each class and different colors for each fuel type(f1)

```{r}
ggplot(data=mpg, mapping = aes(x = hwy, y = cty, color = fl, shape = class)) + geom_point()
mpg
```
```{r}
ggplot(data=mpg, mapping = aes(x = displ, y = hwy)) + geom_point(alpha=0.4, color = "blue")
```


```{r}
ggplot(data=mpg, mapping = aes(x = displ, y = hwy)) + geom_point(alpha=0.4, color = "gray")
```
```{r}
ggplot(data=mpg, mapping = aes(x = displ, y = hwy)) + geom_point(alpha=0.4, color = "chartreuse")
```
```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
    geom_point() +
    facet_wrap(~manufacturer)
```
```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
    geom_point() +
    facet_wrap(year~manufacturer)
```
```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class)) +
    geom_point() +
    facet_wrap(~manufacturer)
```
```{r}
library(ggthemes)
```
```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point() +
  facet_wrap(~manufacturer)
  theme_fivethirtyeight()
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point() +
  facet_wrap(~manufacturer)
  theme_fivethirtyeight()
```


```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point() +
  theme_fivethirtyeight()
```
```{r}
ggplot(mpg, aes(x=drv, y=hwy)) +
  geom_jitter()
```
```{r}
ggplot(mpg, aes(x=drv, y=hwy)) +
  geom_boxplot()
```
```{r}
ggplot(mpg, aes(x=drv, y=hwy)) +
  geom_violin()
```
```{r}
ggplot(mpg, aes(x=displ, y=hwy)) +
  geom_smooth()
```

```{r}
ggplot(mpg, aes(x=displ, y=hwy)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Relationship between engine size and highway mileage",
       x = "Engine size (liters displaced)",
       y = "Highway mileage (miles per gallon)")
```
```{r}
mytheme <- theme_bw() +
  theme(text = element_text(size=16))
```


```{r}
ggplot(mpg, aes(x=displ, y=hwy)) +
  geom_point() +
  geom_smooth() +
  labs(title = "Relationship between engine size and highway mileage",
       x = "Engine size (liters displaced)",
       y = "Highway mileage (miles per gallon)")
mytheme
```

```{r}
ggplot(mpg, aes(x=fl, fill=class))+
  geom_bar(position="fill")
```
```{r}
myplot <- ggplot(mpg, aes(x=fl, fill=class))+
  geom_bar(position="dodge")

ggsave("example_plot.png", plot = myplot, width = 15, height = 15, units = "cm", device = "png")
```
